### ISSUE TITLE
Looks like it failed when it actually succeeded (..,?)

### ISSUE THREAD

**Issue by michaelb** [Prayag2/consave#3]
Hi, 
It looks like consave (when saving the current profile) looks for some directories (.config/Kvantum, .config/klipperrc etc...) and if it does not find them, it prints:

`[Errno 2] No such file or directory: '/home/username/.config/klipperrc'`

to stdout. The program then doesn't display more errors (the other missing dirs) and exit with code 0 (SUCCESS)

This is very confusing, and I can't know if the save file created is correct/complete or not.

**Comment by ben2talk** [comment]
Yes, I got this same message... and have no clue why I should have a 'klipperrc'.

**Comment by selplacei** [comment]
Should be fixed in #2

**Comment by Prayag2** [comment]
Thanks to @selplacei for the fix!
